### ISSUE TITLE
No Copy/Clone for different structures

### ISSUE THREAD

**Issue by artmelancholy** [dahelb/rs-conllu#1]
Hello!

Thank you for your crate, it's so simple for use!

But for some scenarios I'm in great need for traits `Copy, Clone` on base enum and structs: `Upos`,  `Token`, `TokenId`. 
Is it possible to add them?

**Comment by dahelb** [comment]
Hey, thanks for the feedback! I will have a look at this and get back to you asap.

**Comment by dahelb** [comment]
Just released v0.2.0 with your changes!

**Comment by artmelancholy** [comment]
Thank you!
